"""
미국 주요 종목 목록
- S&P500 전체 503개 (하드코딩) + 나스닥 추가 성장주 + ETF
"""

SP500_LARGE = {
    "A": "Agilent Technologies",
    "AAPL": "Apple Inc.",
    "ABBV": "AbbVie",
    "ABNB": "Airbnb",
    "ABT": "Abbott Laboratories",
    "ACGL": "Arch Capital Group",
    "ACN": "Accenture",
    "ADBE": "Adobe Inc.",
    "ADI": "Analog Devices",
    "ADM": "Archer Daniels Midland",
    "ADP": "Automatic Data Processing",
    "ADSK": "Autodesk",
    "AEE": "Ameren",
    "AEP": "American Electric Power",
    "AES": "AES Corporation",
    "AFL": "Aflac",
    "AIG": "American International Group",
    "AIZ": "Assurant",
    "AJG": "Arthur J. Gallagher & Co.",
    "AKAM": "Akamai Technologies",
    "ALB": "Albemarle Corporation",
    "ALGN": "Align Technology",
    "ALL": "Allstate",
    "ALLE": "Allegion",
    "AMAT": "Applied Materials",
    "AMCR": "Amcor",
    "AMD": "Advanced Micro Devices",
    "AME": "Ametek",
    "AMGN": "Amgen",
    "AMP": "Ameriprise Financial",
    "AMT": "American Tower",
    "AMZN": "Amazon",
    "ANET": "Arista Networks",
    "AON": "Aon plc",
    "AOS": "A. O. Smith",
    "APA": "APA Corporation",
    "APD": "Air Products",
    "APH": "Amphenol",
    "APO": "Apollo Global Management",
    "APP": "AppLovin",
    "APTV": "Aptiv",
    "ARE": "Alexandria Real Estate Equities",
    "ARES": "Ares Management",
    "ATO": "Atmos Energy",
    "AVB": "AvalonBay Communities",
    "AVGO": "Broadcom",
    "AVY": "Avery Dennison",
    "AWK": "American Water Works",
    "AXON": "Axon Enterprise",
    "AXP": "American Express",
    "AZO": "AutoZone",
    "BA": "Boeing",
    "BAC": "Bank of America",
    "BALL": "Ball Corporation",
    "BAX": "Baxter International",
    "BBY": "Best Buy",
    "BDX": "Becton Dickinson",
    "BEN": "Franklin Resources",
    "BF-B": "Brown–Forman",
    "BG": "Bunge Global",
    "BIIB": "Biogen",
    "BK": "BNY Mellon",
    "BKNG": "Booking Holdings",
    "BKR": "Baker Hughes",
    "BLDR": "Builders FirstSource",
    "BLK": "BlackRock",
    "BMY": "Bristol Myers Squibb",
    "BR": "Broadridge Financial Solutions",
    "BRK-B": "Berkshire Hathaway",
    "BRO": "Brown & Brown",
    "BSX": "Boston Scientific",
    "BX": "Blackstone Inc.",
    "BXP": "BXP, Inc.",
    "C": "Citigroup",
    "CAG": "Conagra Brands",
    "CAH": "Cardinal Health",
    "CARR": "Carrier Global",
    "CASY": "Casey\'s",
    "CAT": "Caterpillar Inc.",
    "CB": "Chubb Limited",
    "CBOE": "Cboe Global Markets",
    "CBRE": "CBRE Group",
    "CCI": "Crown Castle",
    "CCL": "Carnival",
    "CDNS": "Cadence Design Systems",
    "CDW": "CDW Corporation",
    "CEG": "Constellation Energy",
    "CF": "CF Industries",
    "CFG": "Citizens Financial Group",
    "CHD": "Church & Dwight",
    "CHRW": "C.H. Robinson",
    "CHTR": "Charter Communications",
    "CI": "Cigna",
    "CIEN": "Ciena",
    "CINF": "Cincinnati Financial",
    "CL": "Colgate-Palmolive",
    "CLX": "Clorox",
    "CMCSA": "Comcast",
    "CME": "CME Group",
    "CMG": "Chipotle Mexican Grill",
    "CMI": "Cummins",
    "CMS": "CMS Energy",
    "CNC": "Centene Corporation",
    "CNP": "CenterPoint Energy",
    "COF": "Capital One",
    "COHR": "Coherent Corp.",
    "COIN": "Coinbase",
    "COO": "Cooper Companies (The)",
    "COP": "ConocoPhillips",
    "COR": "Cencora",
    "COST": "Costco",
    "CPAY": "Corpay",
    "CPB": "Campbell\'s Company (The)",
    "CPRT": "Copart",
    "CPT": "Camden Property Trust",
    "CRH": "CRH plc",
    "CRL": "Charles River Laboratories",
    "CRM": "Salesforce",
    "CRWD": "CrowdStrike",
    "CSCO": "Cisco",
    "CSGP": "CoStar Group",
    "CSX": "CSX Corporation",
    "CTAS": "Cintas",
    "CTRA": "Coterra",
    "CTSH": "Cognizant",
    "CTVA": "Corteva",
    "CVNA": "Carvana",
    "CVS": "CVS Health",
    "CVX": "Chevron Corporation",
    "D": "Dominion Energy",
    "DAL": "Delta Air Lines",
    "DASH": "DoorDash",
    "DD": "DuPont",
    "DDOG": "Datadog",
    "DE": "Deere & Company",
    "DECK": "Deckers Brands",
    "DELL": "Dell Technologies",
    "DG": "Dollar General",
    "DGX": "Quest Diagnostics",
    "DHI": "D. R. Horton",
    "DHR": "Danaher Corporation",
    "DIS": "Walt Disney Company (The)",
    "DLR": "Digital Realty",
    "DLTR": "Dollar Tree",
    "DOC": "Healthpeak Properties",
    "DOV": "Dover Corporation",
    "DOW": "Dow Inc.",
    "DPZ": "Domino\'s",
    "DRI": "Darden Restaurants",
    "DTE": "DTE Energy",
    "DUK": "Duke Energy",
    "DVA": "DaVita",
    "DVN": "Devon Energy",
    "DXCM": "Dexcom",
    "EA": "Electronic Arts",
    "EBAY": "eBay Inc.",
    "ECL": "Ecolab",
    "ED": "Consolidated Edison",
    "EFX": "Equifax",
    "EG": "Everest Group",
    "EIX": "Edison International",
    "EL": "Estée Lauder Companies (The)",
    "ELV": "Elevance Health",
    "EME": "Emcor",
    "EMR": "Emerson Electric",
    "EOG": "EOG Resources",
    "EPAM": "EPAM Systems",
    "EQIX": "Equinix",
    "EQR": "Equity Residential",
    "EQT": "EQT Corporation",
    "ERIE": "Erie Indemnity",
    "ES": "Eversource Energy",
    "ESS": "Essex Property Trust",
    "ETN": "Eaton Corporation",
    "ETR": "Entergy",
    "EVRG": "Evergy",
    "EW": "Edwards Lifesciences",
    "EXC": "Exelon",
    "EXE": "Expand Energy",
    "EXPD": "Expeditors International",
    "EXPE": "Expedia Group",
    "EXR": "Extra Space Storage",
    "F": "Ford Motor Company",
    "FANG": "Diamondback Energy",
    "FAST": "Fastenal",
    "FCX": "Freeport-McMoRan",
    "FDS": "FactSet",
    "FDX": "FedEx",
    "FE": "FirstEnergy",
    "FFIV": "F5, Inc.",
    "FICO": "Fair Isaac",
    "FIS": "Fidelity National Information Services",
    "FISV": "Fiserv",
    "FITB": "Fifth Third Bancorp",
    "FIX": "Comfort Systems USA",
    "FOX": "Fox Corporation (Class B)",
    "FOXA": "Fox Corporation (Class A)",
    "FRT": "Federal Realty Investment Trust",
    "FSLR": "First Solar",
    "FTNT": "Fortinet",
    "FTV": "Fortive",
    "GD": "General Dynamics",
    "GDDY": "GoDaddy",
    "GE": "GE Aerospace",
    "GEHC": "GE HealthCare",
    "GEN": "Gen Digital",
    "GEV": "GE Vernova",
    "GILD": "Gilead Sciences",
    "GIS": "General Mills",
    "GL": "Globe Life",
    "GLW": "Corning Inc.",
    "GM": "General Motors",
    "GNRC": "Generac",
    "GOOG": "Alphabet Inc. (Class C)",
    "GOOGL": "Alphabet Inc. (Class A)",
    "GPC": "Genuine Parts Company",
    "GPN": "Global Payments",
    "GRMN": "Garmin",
    "GS": "Goldman Sachs",
    "GWW": "W. W. Grainger",
    "HAL": "Halliburton",
    "HAS": "Hasbro",
    "HBAN": "Huntington Bancshares",
    "HCA": "HCA Healthcare",
    "HD": "Home Depot (The)",
    "HIG": "Hartford (The)",
    "HII": "Huntington Ingalls Industries",
    "HLT": "Hilton Worldwide",
    "HON": "Honeywell",
    "HOOD": "Robinhood Markets",
    "HPE": "Hewlett Packard Enterprise",
    "HPQ": "HP Inc.",
    "HRL": "Hormel Foods",
    "HSIC": "Henry Schein",
    "HST": "Host Hotels & Resorts",
    "HSY": "Hershey Company (The)",
    "HUBB": "Hubbell Incorporated",
    "HUM": "Humana",
    "HWM": "Howmet Aerospace",
    "IBKR": "Interactive Brokers",
    "IBM": "IBM",
    "ICE": "Intercontinental Exchange",
    "IDXX": "Idexx Laboratories",
    "IEX": "IDEX Corporation",
    "IFF": "International Flavors & Fragrances",
    "INCY": "Incyte",
    "INTC": "Intel",
    "INTU": "Intuit",
    "INVH": "Invitation Homes",
    "IP": "International Paper",
    "IQV": "IQVIA",
    "IR": "Ingersoll Rand",
    "IRM": "Iron Mountain",
    "ISRG": "Intuitive Surgical",
    "IT": "Gartner",
    "ITW": "Illinois Tool Works",
    "IVZ": "Invesco",
    "J": "Jacobs Solutions",
    "JBHT": "J.B. Hunt",
    "JBL": "Jabil",
    "JCI": "Johnson Controls",
    "JKHY": "Jack Henry & Associates",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "KDP": "Keurig Dr Pepper",
    "KEY": "KeyCorp",
    "KEYS": "Keysight Technologies",
    "KHC": "Kraft Heinz",
    "KIM": "Kimco Realty",
    "KKR": "KKR & Co.",
    "KLAC": "KLA Corporation",
    "KMB": "Kimberly-Clark",
    "KMI": "Kinder Morgan",
    "KO": "Coca-Cola Company (The)",
    "KR": "Kroger",
    "KVUE": "Kenvue",
    "L": "Loews Corporation",
    "LDOS": "Leidos",
    "LEN": "Lennar",
    "LH": "Labcorp",
    "LHX": "L3Harris",
    "LII": "Lennox International",
    "LIN": "Linde plc",
    "LITE": "Lumentum",
    "LLY": "Lilly (Eli)",
    "LMT": "Lockheed Martin",
    "LNT": "Alliant Energy",
    "LOW": "Lowe\'s",
    "LRCX": "Lam Research",
    "LULU": "Lululemon Athletica",
    "LUV": "Southwest Airlines",
    "LVS": "Las Vegas Sands",
    "LYB": "LyondellBasell",
    "LYV": "Live Nation Entertainment",
    "MA": "Mastercard",
    "MAA": "Mid-America Apartment Communities",
    "MAR": "Marriott International",
    "MAS": "Masco",
    "MCD": "McDonald\'s",
    "MCHP": "Microchip Technology",
    "MCK": "McKesson Corporation",
    "MCO": "Moody\'s Corporation",
    "MDLZ": "Mondelez International",
    "MDT": "Medtronic",
    "MET": "MetLife",
    "META": "Meta Platforms",
    "MGM": "MGM Resorts",
    "MKC": "McCormick & Company",
    "MLM": "Martin Marietta Materials",
    "MMM": "3M",
    "MNST": "Monster Beverage",
    "MO": "Altria",
    "MOS": "Mosaic Company (The)",
    "MPC": "Marathon Petroleum",
    "MPWR": "Monolithic Power Systems",
    "MRK": "Merck & Co.",
    "MRNA": "Moderna",
    "MRSH": "Marsh McLennan",
    "MS": "Morgan Stanley",
    "MSCI": "MSCI Inc.",
    "MSFT": "Microsoft",
    "MSI": "Motorola Solutions",
    "MTB": "M&T Bank",
    "MTD": "Mettler Toledo",
    "MU": "Micron Technology",
    "NCLH": "Norwegian Cruise Line Holdings",
    "NDAQ": "Nasdaq, Inc.",
    "NDSN": "Nordson Corporation",
    "NEE": "NextEra Energy",
    "NEM": "Newmont",
    "NFLX": "Netflix",
    "NI": "NiSource",
    "NKE": "Nike, Inc.",
    "NOC": "Northrop Grumman",
    "NOW": "ServiceNow",
    "NRG": "NRG Energy",
    "NSC": "Norfolk Southern",
    "NTAP": "NetApp",
    "NTRS": "Northern Trust",
    "NUE": "Nucor",
    "NVDA": "Nvidia",
    "NVR": "NVR, Inc.",
    "NWS": "News Corp (Class B)",
    "NWSA": "News Corp (Class A)",
    "NXPI": "NXP Semiconductors",
    "O": "Realty Income",
    "ODFL": "Old Dominion",
    "OKE": "Oneok",
    "OMC": "Omnicom Group",
    "ON": "ON Semiconductor",
    "ORCL": "Oracle Corporation",
    "ORLY": "O’Reilly Automotive",
    "OTIS": "Otis Worldwide",
    "OXY": "Occidental Petroleum",
    "PANW": "Palo Alto Networks",
    "PAYX": "Paychex",
    "PCAR": "Paccar",
    "PCG": "PG&E Corporation",
    "PEG": "Public Service Enterprise Group",
    "PEP": "PepsiCo",
    "PFE": "Pfizer",
    "PFG": "Principal Financial Group",
    "PG": "Procter & Gamble",
    "PGR": "Progressive Corporation",
    "PH": "Parker Hannifin",
    "PHM": "PulteGroup",
    "PKG": "Packaging Corporation of America",
    "PLD": "Prologis",
    "PLTR": "Palantir Technologies",
    "PM": "Philip Morris International",
    "PNC": "PNC Financial Services",
    "PNR": "Pentair",
    "PNW": "Pinnacle West Capital",
    "PODD": "Insulet Corporation",
    "POOL": "Pool Corporation",
    "PPG": "PPG Industries",
    "PPL": "PPL Corporation",
    "PRU": "Prudential Financial",
    "PSA": "Public Storage",
    "PSKY": "Paramount Skydance Corporation",
    "PSX": "Phillips 66",
    "PTC": "PTC Inc.",
    "PWR": "Quanta Services",
    "PYPL": "PayPal",
    "Q": "Qnity Electronics",
    "QCOM": "Qualcomm",
    "RCL": "Royal Caribbean Group",
    "REG": "Regency Centers",
    "REGN": "Regeneron Pharmaceuticals",
    "RF": "Regions Financial Corporation",
    "RJF": "Raymond James Financial",
    "RL": "Ralph Lauren Corporation",
    "RMD": "ResMed",
    "ROK": "Rockwell Automation",
    "ROL": "Rollins, Inc.",
    "ROP": "Roper Technologies",
    "ROST": "Ross Stores",
    "RSG": "Republic Services",
    "RTX": "RTX Corporation",
    "RVTY": "Revvity",
    "SATS": "EchoStar",
    "SBAC": "SBA Communications",
    "SBUX": "Starbucks",
    "SCHW": "Charles Schwab Corporation",
    "SHW": "Sherwin-Williams",
    "SJM": "J.M. Smucker Company (The)",
    "SLB": "Schlumberger",
    "SMCI": "Supermicro",
    "SNA": "Snap-on",
    "SNDK": "Sandisk",
    "SNPS": "Synopsys",
    "SO": "Southern Company",
    "SOLV": "Solventum",
    "SPG": "Simon Property Group",
    "SPGI": "S&P Global",
    "SRE": "Sempra",
    "STE": "Steris",
    "STLD": "Steel Dynamics",
    "STT": "State Street Corporation",
    "STX": "Seagate Technology",
    "STZ": "Constellation Brands",
    "SW": "Smurfit Westrock",
    "SWK": "Stanley Black & Decker",
    "SWKS": "Skyworks Solutions",
    "SYF": "Synchrony Financial",
    "SYK": "Stryker Corporation",
    "SYY": "Sysco",
    "T": "AT&T",
    "TAP": "Molson Coors Beverage Company",
    "TDG": "TransDigm Group",
    "TDY": "Teledyne Technologies",
    "TECH": "Bio-Techne",
    "TEL": "TE Connectivity",
    "TER": "Teradyne",
    "TFC": "Truist Financial",
    "TGT": "Target Corporation",
    "TJX": "TJX Companies",
    "TKO": "TKO Group Holdings",
    "TMO": "Thermo Fisher Scientific",
    "TMUS": "T-Mobile US",
    "TPL": "Texas Pacific Land Corporation",
    "TPR": "Tapestry, Inc.",
    "TRGP": "Targa Resources",
    "TRMB": "Trimble Inc.",
    "TROW": "T. Rowe Price",
    "TRV": "Travelers Companies (The)",
    "TSCO": "Tractor Supply",
    "TSLA": "Tesla, Inc.",
    "TSN": "Tyson Foods",
    "TT": "Trane Technologies",
    "TTD": "Trade Desk (The)",
    "TTWO": "Take-Two Interactive",
    "TXN": "Texas Instruments",
    "TXT": "Textron",
    "TYL": "Tyler Technologies",
    "UAL": "United Airlines Holdings",
    "UBER": "Uber",
    "UDR": "UDR, Inc.",
    "UHS": "Universal Health Services",
    "ULTA": "Ulta Beauty",
    "UNH": "UnitedHealth Group",
    "UNP": "Union Pacific Corporation",
    "UPS": "United Parcel Service",
    "URI": "United Rentals",
    "USB": "U.S. Bancorp",
    "V": "Visa Inc.",
    "VICI": "Vici Properties",
    "VLO": "Valero Energy",
    "VLTO": "Veralto",
    "VMC": "Vulcan Materials Company",
    "VRSK": "Verisk Analytics",
    "VRSN": "Verisign",
    "VRT": "Vertiv",
    "VRTX": "Vertex Pharmaceuticals",
    "VST": "Vistra Corp.",
    "VTR": "Ventas",
    "VTRS": "Viatris",
    "VZ": "Verizon",
    "WAB": "Wabtec",
    "WAT": "Waters Corporation",
    "WBD": "Warner Bros. Discovery",
    "WDAY": "Workday, Inc.",
    "WDC": "Western Digital",
    "WEC": "WEC Energy Group",
    "WELL": "Welltower",
    "WFC": "Wells Fargo",
    "WM": "Waste Management",
    "WMB": "Williams Companies",
    "WMT": "Walmart",
    "WRB": "W. R. Berkley Corporation",
    "WSM": "Williams-Sonoma, Inc.",
    "WST": "West Pharmaceutical Services",
    "WTW": "Willis Towers Watson",
    "WY": "Weyerhaeuser",
    "WYNN": "Wynn Resorts",
    "XEL": "Xcel Energy",
    "XOM": "ExxonMobil",
    "XYL": "Xylem Inc.",
    "XYZ": "Block, Inc.",
    "YUM": "Yum! Brands",
    "ZBH": "Zimmer Biomet",
    "ZBRA": "Zebra Technologies",
    "ZTS": "Zoetis",
}

# 나스닥 추가 성장주 (S&P500에 없는 것)
NASDAQ_EXTRA = {
    "NVDA": "엔비디아", "AMD": "AMD", "ADBE": "어도비", "QCOM": "퀄컴",
    "AMAT": "어플라이드머티리얼즈", "MU": "마이크론", "LRCX": "램리서치",
    "KLAC": "KLA코퍼레이션", "MRVL": "마벨테크놀로지", "ASML": "ASML",
    "PANW": "팔로알토네트웍스", "CRWD": "크라우드스트라이크", "SNPS": "시놉시스",
    "CDNS": "케이던스", "FTNT": "포티넷", "MCHP": "마이크로칩테크놀로지",
    "ON": "온세미컨덕터", "NXPI": "NXP세미컨덕터",
    "ABNB": "에어비앤비", "BKNG": "부킹홀딩스", "EXPE": "익스피디아",
    "ZM": "줌", "TEAM": "아틀라시안", "WDAY": "워크데이",
    "OKTA": "옥타", "DDOG": "데이터독", "SNOW": "스노우플레이크",
    "PLTR": "팔란티어", "RBLX": "로블록스", "UBER": "우버",
    "LYFT": "리프트", "DASH": "도어대시", "COIN": "코인베이스",
    "ORCL": "오라클", "CRM": "세일즈포스", "NOW": "서비스나우",
    "SHOP": "쇼피파이", "SQ": "블록", "TWLO": "트윌리오",
    "ZS": "지스케일러", "NET": "클라우드플레어", "HUBS": "허브스팟",
    "BILL": "빌닷컴", "GTLB": "깃랩", "MDB": "몽고DB",
    "ESTC": "엘라스틱", "CFLT": "컨플루언트", "U": "유니티",
    "APP": "앱러빈", "TTD": "더트레이드데스크", "ROKU": "로쿠",
    "SPOT": "스포티파이", "PINS": "핀터레스트", "SNAP": "스냅",
}

# ETF
ETFS = {
    "SPY": "S&P500 ETF", "QQQ": "나스닥100 ETF", "IWM": "러셀2000 ETF",
    "DIA": "다우존스 ETF", "VTI": "전체시장 ETF", "VOO": "뱅가드S&P500",
    "XLK": "기술주 ETF", "XLF": "금융 ETF", "XLE": "에너지 ETF",
    "XLV": "헬스케어 ETF", "XLY": "소비재 ETF", "XLI": "산업재 ETF",
    "XLC": "통신 ETF", "XLB": "소재 ETF", "XLRE": "부동산 ETF",
    "ARKK": "ARK이노베이션", "ARKG": "ARK게노믹스", "ARKW": "ARK인터넷",
    "SOXX": "반도체 ETF", "SMH": "반도체 ETF2", "SOXL": "반도체3배",
    "GLD": "금 ETF", "SLV": "은 ETF", "TLT": "장기국채 ETF",
    "HYG": "하이일드채권", "LQD": "투자등급채권",
    "VNQ": "부동산 ETF", "IEMG": "신흥국 ETF", "EFA": "선진국 ETF",
}

# 전체 합산 (중복 제거)
NASDAQ_100 = {**SP500_LARGE, **NASDAQ_EXTRA}
ALL_SYMBOLS = {**SP500_LARGE, **NASDAQ_EXTRA, **ETFS}


def get_symbols_by_category():
    return {
        "S&P500 전체": SP500_LARGE,
        "나스닥 추가": NASDAQ_EXTRA,
        "ETF": ETFS,
    }
